version: '3'
services:
  elasticsearch:
    platform: linux/amd64
    build: ./elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch71-data:/usr/share/elasticsearch/data"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana-oss:7.1.1
    ports:
      - "5601:5601"
volumes:
  elasticsearch71-data:
    driver: local
