version: '3'
services:
  tidb:
    platform: linux/amd64
    build: .
    ports:
      - "4000:4000" # tidb port: mysql -u root -h127.0.0.1 -P4000
      - "2379:2379" # dashboard port: http://localhost:2379/dashboard/
    volumes:
      - "tidb-v7_1_1-data:/root/.tiup/data/v7_1_1"
volumes:
  tidb-v7_1_1-data:
    driver: local
