version: '3'
services:
  upsource:
    image: jetbrains/upsource:2018.2.1154
    ports:
      - "6780:8080"
    volumes:
      - upsource-data:/opt/upsource/data
      - upsource-conf:/opt/upsource/conf
      - upsource-logs:/opt/upsource/logs
      - upsource-backups:/opt/upsource/backups
volumes:
  upsource-data:
    driver: local
  upsource-conf:
    driver: local
  upsource-logs:
    driver: local
  upsource-backups:
    driver: local
