version: '3'
services:
  oracle:
    image: sath89/oracle-12c
    ports:
      - "1521:1521"
      - "8080:8080"
    environment:
      CHARACTER_SET: JA16SJIS
    volumes:
      - oracle-data:/u01/app/oracle sath89/oracle-12c
    restart: always
  mysql:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max_allowed_packet=32505856
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
volumes:
  mysql-data:
    driver: local
  oracle-data:
    driver: local
