services:
  elasticsearch:
    platform: linux/amd64
    build: ./elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch_data_8_15_3:/usr/share/elasticsearch/data"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
    networks:
      - elasticsearch_net_8_15_3
  kibana:
    platform: linux/amd64
    image: docker.elastic.co/kibana/kibana:8.15.3
    ports:
      - "5601:5601"
    networks:
      - elasticsearch_net_8_15_3
volumes:
  elasticsearch_data_8_15_3:
    driver: local
networks:
  elasticsearch_net_8_15_3:
