version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9263:9200"
    volumes:
      - "elasticsearch63-data:/usr/share/elasticsearch/data"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.3.2
    ports:
      - "5663:5601"
volumes:
  elasticsearch63-data:
    driver: local
