version: '3'
services:
  elasticsearch:
    build: ./elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - "elasticsearch55-data:/usr/share/elasticsearch/data"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    restart: always
  kibana:
    image: kibana:5.5
    ports:
      - "5601:5601"
    restart: always
volumes:
  elasticsearch55-data:
    driver: local
